/*
Copyright 2022 The fornax-serverless Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	corev1 "centaurusinfra.io/fornax-serverless/pkg/apis/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIngressEndpoints implements IngressEndpointInterface
type FakeIngressEndpoints struct {
	Fake *FakeCoreV1
	ns   string
}

var ingressendpointsResource = schema.GroupVersionResource{Group: "core.fornax-serverless.centaurusinfra.io", Version: "v1", Resource: "ingressendpoints"}

var ingressendpointsKind = schema.GroupVersionKind{Group: "core.fornax-serverless.centaurusinfra.io", Version: "v1", Kind: "IngressEndpoint"}

// Get takes name of the ingressEndpoint, and returns the corresponding ingressEndpoint object, and an error if there is any.
func (c *FakeIngressEndpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *corev1.IngressEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ingressendpointsResource, c.ns, name), &corev1.IngressEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.IngressEndpoint), err
}

// List takes label and field selectors, and returns the list of IngressEndpoints that match those selectors.
func (c *FakeIngressEndpoints) List(ctx context.Context, opts v1.ListOptions) (result *corev1.IngressEndpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ingressendpointsResource, ingressendpointsKind, c.ns, opts), &corev1.IngressEndpointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &corev1.IngressEndpointList{ListMeta: obj.(*corev1.IngressEndpointList).ListMeta}
	for _, item := range obj.(*corev1.IngressEndpointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ingressEndpoints.
func (c *FakeIngressEndpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ingressendpointsResource, c.ns, opts))

}

// Create takes the representation of a ingressEndpoint and creates it.  Returns the server's representation of the ingressEndpoint, and an error, if there is any.
func (c *FakeIngressEndpoints) Create(ctx context.Context, ingressEndpoint *corev1.IngressEndpoint, opts v1.CreateOptions) (result *corev1.IngressEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ingressendpointsResource, c.ns, ingressEndpoint), &corev1.IngressEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.IngressEndpoint), err
}

// Update takes the representation of a ingressEndpoint and updates it. Returns the server's representation of the ingressEndpoint, and an error, if there is any.
func (c *FakeIngressEndpoints) Update(ctx context.Context, ingressEndpoint *corev1.IngressEndpoint, opts v1.UpdateOptions) (result *corev1.IngressEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ingressendpointsResource, c.ns, ingressEndpoint), &corev1.IngressEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.IngressEndpoint), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIngressEndpoints) UpdateStatus(ctx context.Context, ingressEndpoint *corev1.IngressEndpoint, opts v1.UpdateOptions) (*corev1.IngressEndpoint, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ingressendpointsResource, "status", c.ns, ingressEndpoint), &corev1.IngressEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.IngressEndpoint), err
}

// Delete takes name of the ingressEndpoint and deletes it. Returns an error if one occurs.
func (c *FakeIngressEndpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ingressendpointsResource, c.ns, name, opts), &corev1.IngressEndpoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIngressEndpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ingressendpointsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &corev1.IngressEndpointList{})
	return err
}

// Patch applies the patch and returns the patched ingressEndpoint.
func (c *FakeIngressEndpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1.IngressEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ingressendpointsResource, c.ns, name, pt, data, subresources...), &corev1.IngressEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.IngressEndpoint), err
}
