/*
Copyright 2022 The fornax-serverless Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	corev1 "centaurusinfra.io/fornax-serverless/pkg/apis/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeApplicationSessions implements ApplicationSessionInterface
type FakeApplicationSessions struct {
	Fake *FakeCoreV1
	ns   string
}

var applicationsessionsResource = schema.GroupVersionResource{Group: "core.fornax-serverless.centaurusinfra.io", Version: "v1", Resource: "applicationsessions"}

var applicationsessionsKind = schema.GroupVersionKind{Group: "core.fornax-serverless.centaurusinfra.io", Version: "v1", Kind: "ApplicationSession"}

// Get takes name of the applicationSession, and returns the corresponding applicationSession object, and an error if there is any.
func (c *FakeApplicationSessions) Get(ctx context.Context, name string, options v1.GetOptions) (result *corev1.ApplicationSession, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(applicationsessionsResource, c.ns, name), &corev1.ApplicationSession{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.ApplicationSession), err
}

// List takes label and field selectors, and returns the list of ApplicationSessions that match those selectors.
func (c *FakeApplicationSessions) List(ctx context.Context, opts v1.ListOptions) (result *corev1.ApplicationSessionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(applicationsessionsResource, applicationsessionsKind, c.ns, opts), &corev1.ApplicationSessionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &corev1.ApplicationSessionList{ListMeta: obj.(*corev1.ApplicationSessionList).ListMeta}
	for _, item := range obj.(*corev1.ApplicationSessionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested applicationSessions.
func (c *FakeApplicationSessions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(applicationsessionsResource, c.ns, opts))

}

// Create takes the representation of a applicationSession and creates it.  Returns the server's representation of the applicationSession, and an error, if there is any.
func (c *FakeApplicationSessions) Create(ctx context.Context, applicationSession *corev1.ApplicationSession, opts v1.CreateOptions) (result *corev1.ApplicationSession, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(applicationsessionsResource, c.ns, applicationSession), &corev1.ApplicationSession{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.ApplicationSession), err
}

// Update takes the representation of a applicationSession and updates it. Returns the server's representation of the applicationSession, and an error, if there is any.
func (c *FakeApplicationSessions) Update(ctx context.Context, applicationSession *corev1.ApplicationSession, opts v1.UpdateOptions) (result *corev1.ApplicationSession, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(applicationsessionsResource, c.ns, applicationSession), &corev1.ApplicationSession{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.ApplicationSession), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeApplicationSessions) UpdateStatus(ctx context.Context, applicationSession *corev1.ApplicationSession, opts v1.UpdateOptions) (*corev1.ApplicationSession, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(applicationsessionsResource, "status", c.ns, applicationSession), &corev1.ApplicationSession{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.ApplicationSession), err
}

// Delete takes name of the applicationSession and deletes it. Returns an error if one occurs.
func (c *FakeApplicationSessions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(applicationsessionsResource, c.ns, name, opts), &corev1.ApplicationSession{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeApplicationSessions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(applicationsessionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &corev1.ApplicationSessionList{})
	return err
}

// Patch applies the patch and returns the patched applicationSession.
func (c *FakeApplicationSessions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1.ApplicationSession, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(applicationsessionsResource, c.ns, name, pt, data, subresources...), &corev1.ApplicationSession{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.ApplicationSession), err
}
