/*
Copyright 2022 The fornax-serverless Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	corev1 "centaurusinfra.io/fornax-serverless/pkg/apis/core/v1"
	versioned "centaurusinfra.io/fornax-serverless/pkg/client/clientset/versioned"
	internalinterfaces "centaurusinfra.io/fornax-serverless/pkg/client/informers/externalversions/internalinterfaces"
	v1 "centaurusinfra.io/fornax-serverless/pkg/client/listers/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IngressEndpointInformer provides access to a shared informer and lister for
// IngressEndpoints.
type IngressEndpointInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.IngressEndpointLister
}

type ingressEndpointInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIngressEndpointInformer constructs a new informer for IngressEndpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIngressEndpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIngressEndpointInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIngressEndpointInformer constructs a new informer for IngressEndpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIngressEndpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1().IngressEndpoints(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1().IngressEndpoints(namespace).Watch(context.TODO(), options)
			},
		},
		&corev1.IngressEndpoint{},
		resyncPeriod,
		indexers,
	)
}

func (f *ingressEndpointInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIngressEndpointInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ingressEndpointInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&corev1.IngressEndpoint{}, f.defaultInformer)
}

func (f *ingressEndpointInformer) Lister() v1.IngressEndpointLister {
	return v1.NewIngressEndpointLister(f.Informer().GetIndexer())
}
