#!/usr/bin/env bash


FORNAX_ROOT=$(dirname "${BASH_SOURCE}")/../../..

###GCE/GCLOUD common ENV
GCLOUD=gcloud
ZONE=${FORNAX_GCE_ZONE:-us-central1-a}
REGION=${ZONE%-*}
PROJECT=${FORNAX_GCE_PROJECT:-workload-controller-manager}
INSTANCE_PREFIX=${FORNAX_INSTANCE_PREFIX:-fornax}
SERVICE_ACCOUNT=${SERVICE_ACCOUNT:-default}


###fornaxcore machine setup ENV
CORE_INSTANCE_PREFIX=${CORE_INSTANCE_PREFIX:-"${INSTANCE_PREFIX}-core"}
CORE_MACHINE_TYPE=${CORE_MACHINE_TYPE:-n1-standard-4}
CORE_DISK_TYPE=${CORE_DISK_TYPE:-pd-ssd}
CORE_DISK_SIZE=${CORE_DISK_SIZE:-40}
CORE_IMAGE_PROJECT=${CORE_IMAGE_PROJECT:-ubuntu-os-cloud}
CORE_IMAGE=${CORE_IMAGE:-ubuntu-2004-focal-v20221018}
CORE_SERVICE_ACCOUNT=${SERVICE_ACCOUNT:-default}



###fornaxnode machine setup ENV
NODE_NUM=${NODE_NUM:-2}
NODE_INSTANCE_PREFIX=${NODE_INSTANCE_PREFIX:-"${INSTANCE_PREFIX}-node"}
NODE_MACHINE_TYPE=${NODE_MACHINE_TYPE:-n1-standard-32}
NODE_DISK_TYPE=${NODE_DISK_TYPE:-pd-ssd}
NODE_DISK_SIZE=${NODE_DISK_SIZE:-30}
NODE_IMAGE_PROJECT=${NODE_IMAGE_PROJECT:-ubuntu-os-cloud}
NODE_IMAGE=${NODE_IMAGE:-ubuntu-2004-focal-v20221018}
NODE_SERVICE_ACCOUNT=${SERVICE_ACCOUNT:-default}


###fornax service common ENV

CORE_AUTO_START=${CORE_AUTO_START:-true}
NODEAGENT_AUTO_START=${NODEAGENT_AUTO_START:-true}
SIM_AUTO_START=${SIM_AUTO_START:-false}

###fornaxcore service ENV
CORE_ETCD_SERVERS=${CORE_ETCD_SERVERS:-http://127.0.0.1:2379}
CORE_SECURE_PORT=${CORE_SECURE_PORT:-9443}
CORE_BIND_ADDRESS=${CORE_BIND_ADDRESS:-127.0.0.1}
CORE_LOG_FILE=${CORE_LOG_FILE:-fornaxcore-$(date '+%s').log}
CORE_STANDALONE_DEBUG_MODE=${CORE_STANDALONE_DEBUG_MODE:-true}
CORE_DEFAULT_PORT=${CORE_DEFAULT_PORT:-18001}


###fornaxnodeagent service ENV
NODE_DISABLE_SWAP=${NODE_DISABLE_SWAP:-false}
NODE_LOG_FILE=${NODE_LOG_FILE:-nodeagent-$(date '+%s').log}


###simulatenodes service ENV
SIM_NUM_OF_NODE=${SIM_NUM_OF_NODE:-100}
SIM_LOG_FILE=${SIM_LOG_FILE:-simulatenode-$(date '+%s').log}


###fornaxtest ENV
TEST_NUM_OF_SESSION_PER_APP=${TEST_NUM_OF_SESSION_PER_APP:-10}
TEST_NUM_OF_APP=${TEST_NUM_OF_APP:-1}
TEST_NUM_OF_INIT_POD_PER_APP=${TEST_NUM_OF_INIT_POD_PER_APP:-0}
TEST_NUM_OF_BURST_POD_PER_APP=${TEST_NUM_OF_BURST_POD_PER_APP:-10}
TEST_NUM_OF_TEST_CYCLE=${TEST_NUM_OF_TEST_CYCLE:-1}
TEST_LOG_FILE=${TEST_LOG_FILE:-fornaxtest-$(date '+%s').log}
TEST_AUTO_START=${TEST_AUTO_START:-false}

###log collection ENV
LOG_AUTO_COLLECT=${LOG_AUTO_COLLECT:-false}
LOG_DIR_LOCAL=${LOG_DIR_LOCAL:-~/logs/fornax/fornaxtest}