apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: sample-system # {"$kpt-set":"namespace"}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    apiserver: "true"
