apiVersion: core.fornax-serverless.centaurusinfra.io/v1
kind: ApplicationInstance
metadata:
  name: nginx-instance-1
  labels:
    name: nginx-instance-1
  ownerReferences:
    - apiVersion: core.fornax-serverless.centaurusinfra.io/v1
      kind: Application
      name: nginx2
      uid: ad834522-d9a5-4841-beac-991ff3798c00
spec:
  application_name: nginx-instance-1
  instance_name: nginx-instance-1
  instance_interfaces:
    - ip_address: 10.0.0.1
      vpc: my-nice-vpc
status:
  status: standby
  history:
    - pod_reference:
        name: nginx-instance-pod-2
      action: createPod
      update_time: 2020-10-01T12:00:00.000Z
    - pod_reference:
        name: nginx-instance-pod-1
      action: deletePod
      update_time: 2020-10-01T11:00:00.000Z
    - pod_reference:
        name: nginx-instance-pod-1
      action: createPod
      update_time: 2020-10-01T10:00:00.000Z
