apiVersion: core.fornax-serverless.centaurusinfra.io/v1
kind: Application
metadata:
  name: nginx2
  labels:
    name: nginx-undo
spec:
  sessionConfig:
    numOfSessionOfInstance: 1
    minSessions: 1
    maxSessions: 10
    maxSurge: 1
    minOfIdleSessions: 0
  container:
    image: nginx
    name: nginx
  workingMode: Standlone
  configData:
    config1: data1
    config2: data2
status:
  deployementStatus: Progressing
  deploymentTime: 2020-10-01T12:00:00.000Z
  desiredInstances: 10
  availableInstances: 1
  history:
    - status: Progressing
      action: createInstance
      updateTime: 2020-10-01T10:00:00.000Z
      instanceReference:
        name: nginx-instance-1
    - status: Progressing
      action: deleteInstance
      updateTime: 2020-10-01T10:00:00.000Z
      instanceReference:
        name: nginx-instance-0
