apiVersion: core.fornax-serverless.centaurusinfra.io/v1
kind: ApplicationSession
metadata:
  name: nginx-session-1
  labels:
    application: nginx2
spec:
  session_name: my-nginx2-session
  session_data: my-nginx2-session-data
status:
  session_status: Allocated
  client_sessions:
    - name: client-session-1
  history:
    - action: ClientJoin
      update_time: 2020-10-01T10:00:00.000Z
      client_session:
        name: client-session-1
