apiVersion: core.fornax-serverless.centaurusinfra.io/v1
kind: ApplicationSession
metadata:
  name: nginx-session-1
  labels:
    application: nginx2
  ownerReferences:
  - apiVersion: core.fornax-serverless.centaurusinfra.io/v1
    kind: Application
    name: nginx2
    uid: ad834522-d9a5-4841-beac-991ff3798c00
spec:
  sessionName: my-nginx2-session
  sessionData: my-nginx2-session-data
status:
  ingressEndpointReference:
    name: endpoint-reference-1
  sessionStatus: Allocated
  clientSessions:
    - name: client-session-1
  history:
    - action: ClientJoin
      updateTime: 2020-10-01T10:00:00.000Z
      clientSession:
        name: client-session-1
