apiVersion: core.fornax-serverless.centaurusinfra.io/v1
kind: ApplicationSession
metadata:
  name: nginx-session-1
  labels:
    application: nginx2
spec:
  sessionName: my-nginx2-session
  sessionData: my-nginx2-session-data
status:
  ingressEndpointReference:
    name: endpoint-reference-1
  sessionStatus: Allocated
  clientSessions:
    - name: client-session-1
  history:
    - action: ClientJoin
      updateTime: 2020-10-01T10:00:00.000Z
      clientSession:
        name: client-session-1
