apiVersion: core.fornax-serverless.centaurusinfra.io/v1
kind: IngressEndpoint
metadata:
  name: nginx-endpoint-1
  ownerReferences:
    - apiVersion: core.fornax-serverless.centaurusinfra.io/v1
      kind: ApplicationInstance
      name: nginx-instance-1
      uid: ad834522-d9a5-4841-beac-991ff3798c00
    - apiVersion: core.fornax-serverless.centaurusinfra.io/v1
      kind: ApplicationSession
      name: nginx-session-1
      uid: ad834522-d9a5-4841-beac-991ff3798c00
  labels:
    name: nginx-endpoint
spec:
  protocol: TCP
  ingress_gwip_address: 172.13.0.1
  ingress_port: 30001
  destinations:
    - ip_address: 192.168.1
      port: 8000
status:
  service_status: Idle
  history:
    - action: SetupIngressRule
      update_time: 2020-10-01T10:00:00.000Z
