apiVersion: core.fornax-serverless.centaurusinfra.io/v1
kind: Application
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  scalingPolicy:
    minimumInstance: 0
    maximumInstance: 30
    burst: 1
    scalingPolicyType: idle_session_number
    idleSessionNumThreshold:
      highWaterMark: 3
      lowWaterMark: 0
  containers:
    - image: nginx:latest
      name: nginx
      resources:
        requests:
          memory: "500M"
          cpu: "0.5"
        limits:
          memory: "500M"
          cpu: "0.5"
      ports:
        - containerPort: 80
          name: nginx
  configData:
    config1: data1
    config2: data2
