apiVersion: core.fornax-serverless.centaurusinfra.io/v1
kind: Application
metadata:
  name: sessionwrapper-sleep
  labels:
    name: nginx
spec:
  scalingPolicy:
    minimumInstance: 1
    maximumInstance: 30
    burst: 1
    scalingPolicyType: idle_session_number
    idleSessionNumThreshold:
      highWaterMark: 3
      lowWaterMark: 1
  containers:
    - image: centaurusinfra.io/fornax-serverless/session-wrapper:v0.1.0
      name: nginx
      env:
        - name: SESSION_WRAPPER_OPEN_SESSION_CMD
          value: "/opt/bin/sessionwrapper-sleep"
      resources:
        requests:
          memory: "50M"
          cpu: "0.1"
        limits:
          memory: "50M"
          cpu: "0.1"
      ports:
        - containerPort: 80
          name: nginx
  configData:
    config1: data1
    config2: data2
