/*
Copyright 2022 The fornax-serverless Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "centaurusinfra.io/fornax-serverless/pkg/apis/core/v1"
	scheme "centaurusinfra.io/fornax-serverless/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ApplicationSessionsGetter has a method to return a ApplicationSessionInterface.
// A group's client should implement this interface.
type ApplicationSessionsGetter interface {
	ApplicationSessions(namespace string) ApplicationSessionInterface
}

// ApplicationSessionInterface has methods to work with ApplicationSession resources.
type ApplicationSessionInterface interface {
	Create(ctx context.Context, applicationSession *v1.ApplicationSession, opts metav1.CreateOptions) (*v1.ApplicationSession, error)
	Update(ctx context.Context, applicationSession *v1.ApplicationSession, opts metav1.UpdateOptions) (*v1.ApplicationSession, error)
	UpdateStatus(ctx context.Context, applicationSession *v1.ApplicationSession, opts metav1.UpdateOptions) (*v1.ApplicationSession, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ApplicationSession, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ApplicationSessionList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ApplicationSession, err error)
	ApplicationSessionExpansion
}

// applicationSessions implements ApplicationSessionInterface
type applicationSessions struct {
	client rest.Interface
	ns     string
}

// newApplicationSessions returns a ApplicationSessions
func newApplicationSessions(c *CoreV1Client, namespace string) *applicationSessions {
	return &applicationSessions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the applicationSession, and returns the corresponding applicationSession object, and an error if there is any.
func (c *applicationSessions) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ApplicationSession, err error) {
	result = &v1.ApplicationSession{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("applicationsessions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ApplicationSessions that match those selectors.
func (c *applicationSessions) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ApplicationSessionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ApplicationSessionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("applicationsessions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested applicationSessions.
func (c *applicationSessions) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("applicationsessions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a applicationSession and creates it.  Returns the server's representation of the applicationSession, and an error, if there is any.
func (c *applicationSessions) Create(ctx context.Context, applicationSession *v1.ApplicationSession, opts metav1.CreateOptions) (result *v1.ApplicationSession, err error) {
	result = &v1.ApplicationSession{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("applicationsessions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(applicationSession).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a applicationSession and updates it. Returns the server's representation of the applicationSession, and an error, if there is any.
func (c *applicationSessions) Update(ctx context.Context, applicationSession *v1.ApplicationSession, opts metav1.UpdateOptions) (result *v1.ApplicationSession, err error) {
	result = &v1.ApplicationSession{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("applicationsessions").
		Name(applicationSession.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(applicationSession).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *applicationSessions) UpdateStatus(ctx context.Context, applicationSession *v1.ApplicationSession, opts metav1.UpdateOptions) (result *v1.ApplicationSession, err error) {
	result = &v1.ApplicationSession{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("applicationsessions").
		Name(applicationSession.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(applicationSession).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the applicationSession and deletes it. Returns an error if one occurs.
func (c *applicationSessions) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("applicationsessions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *applicationSessions) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("applicationsessions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched applicationSession.
func (c *applicationSessions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ApplicationSession, err error) {
	result = &v1.ApplicationSession{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("applicationsessions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
