name: fornax-serverless-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run check
      run: make check
      
    - name: Run build
      run: make build

    - name: Run test
      run: make test
